// DoListic - ToDo Website Tailwind CSS Configuration

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primary Colors with Shades
        "primary-50": "var(--primary-50)",
        "primary-100": "var(--primary-100)",
        "primary-200": "var(--primary-200)",
        "primary-300": "var(--primary-300)",
        "primary-400": "var(--primary-400)",
        "primary-500": "var(--primary-500)",
        "primary-600": "var(--primary-600)",
        "primary-700": "var(--primary-700)",
        "primary-800": "var(--primary-800)",
        "primary-900": "var(--primary-900)",
        primary: "var(--primary)",

        // Secondary Colors with Shades
        "secondary-50": "var(--secondary-50)",
        "secondary-100": "var(--secondary-100)",
        "secondary-200": "var(--secondary-200)",
        "secondary-300": "var(--secondary-300)",
        "secondary-400": "var(--secondary-400)",
        "secondary-500": "var(--secondary-500)",
        "secondary-600": "var(--secondary-600)",
        "secondary-700": "var(--secondary-700)",
        "secondary-800": "var(--secondary-800)",
        "secondary-900": "var(--secondary-900)",
        secondary: "var(--secondary)",

        // Accent Colors with Shades
        "accent-50": "var(--accent-50)",
        "accent-100": "var(--accent-100)",
        "accent-200": "var(--accent-200)",
        "accent-300": "var(--accent-300)",
        "accent-400": "var(--accent-400)",
        "accent-500": "var(--accent-500)",
        "accent-600": "var(--accent-600)",
        "accent-700": "var(--accent-700)",
        "accent-800": "var(--accent-800)",
        "accent-900": "var(--accent-900)",
        accent: "var(--accent)",

        // Neutral Colors
        "neutral-50": "var(--neutral-50)",
        "neutral-100": "var(--neutral-100)",
        "neutral-200": "var(--neutral-200)",
        "neutral-300": "var(--neutral-300)",
        "neutral-400": "var(--neutral-400)",
        "neutral-500": "var(--neutral-500)",
        "neutral-600": "var(--neutral-600)",
        "neutral-700": "var(--neutral-700)",
        "neutral-800": "var(--neutral-800)",
        "neutral-900": "var(--neutral-900)",

        // Background Colors
        "bg-main": "var(--bg-main)",
        "bg-secondary": "var(--bg-secondary)",
        "bg-tertiary": "var(--bg-tertiary)",
        "bg-card": "var(--bg-card)",
        "bg-hover": "var(--bg-hover)",
        "bg-active": "var(--bg-active)",
        "bg-disabled": "var(--bg-disabled)",
        "bg-overlay": "var(--bg-overlay)",

        // Text Colors
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-tertiary": "var(--text-tertiary)",
        "text-muted": "var(--text-muted)",
        "text-disabled": "var(--text-disabled)",
        "text-white": "var(--text-white)",
        "text-black": "var(--text-black)",
        "text-inverse": "var(--text-inverse)",

        // Border Colors
        "border-light": "var(--border-light)",
        "border-medium": "var(--border-medium)",
        "border-dark": "var(--border-dark)",
        "border-focus": "var(--border-focus)",
        "border-error": "var(--border-error)",
        "border-success": "var(--border-success)",
        "border-warning": "var(--border-warning)",

        // Status Colors with Shades
        "success-50": "var(--success-50)",
        "success-100": "var(--success-100)",
        "success-200": "var(--success-200)",
        "success-300": "var(--success-300)",
        "success-400": "var(--success-400)",
        "success-500": "var(--success-500)",
        "success-600": "var(--success-600)",
        "success-700": "var(--success-700)",
        "success-800": "var(--success-800)",
        "success-900": "var(--success-900)",
        success: "var(--success)",

        "warning-50": "var(--warning-50)",
        "warning-100": "var(--warning-100)",
        "warning-200": "var(--warning-200)",
        "warning-300": "var(--warning-300)",
        "warning-400": "var(--warning-400)",
        "warning-500": "var(--warning-500)",
        "warning-600": "var(--warning-600)",
        "warning-700": "var(--warning-700)",
        "warning-800": "var(--warning-800)",
        "warning-900": "var(--warning-900)",
        warning: "var(--warning)",

        "error-50": "var(--error-50)",
        "error-100": "var(--error-100)",
        "error-200": "var(--error-200)",
        "error-300": "var(--error-300)",
        "error-400": "var(--error-400)",
        "error-500": "var(--error-500)",
        "error-600": "var(--error-600)",
        "error-700": "var(--error-700)",
        "error-800": "var(--error-800)",
        "error-900": "var(--error-900)",
        error: "var(--error)",

        "info-50": "var(--info-50)",
        "info-100": "var(--info-100)",
        "info-200": "var(--info-200)",
        "info-300": "var(--info-300)",
        "info-400": "var(--info-400)",
        "info-500": "var(--info-500)",
        "info-600": "var(--info-600)",
        "info-700": "var(--info-700)",
        "info-800": "var(--info-800)",
        "info-900": "var(--info-900)",
        info: "var(--info)",
      },
      boxShadow: {
        "custom-xs": "var(--shadow-xs)",
        "custom-sm": "var(--shadow-sm)",
        "custom-md": "var(--shadow-md)",
        "custom-lg": "var(--shadow-lg)",
        "custom-xl": "var(--shadow-xl)",
        "custom-2xl": "var(--shadow-2xl)",
        "custom-inner": "var(--shadow-inner)",
        "focus-ring": "var(--focus-ring)",
      },
      opacity: {
        hover: "var(--hover-opacity)",
        active: "var(--active-opacity)",
        disabled: "var(--disabled-opacity)",
      },
    },
  },
  plugins: [],
};
